import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {runInNewContext} from 'node:vm';
import {createSourceFile,ScriptTarget,isFunctionDeclaration} from 'typescript';
import {activityRegisterView,activityRegisterPage} from '../packages/runtime-api/src/activity-register-page';
import {pageProjectResponse,recordDetailPage} from '../packages/runtime-api/src/response-paging';
import {cmengUatHtml} from '../packages/runtime-api/src/ui';
import {projectSourceLabels} from '../packages/runtime-api/src/project-presentation';
import {responseSourceLabels} from '../packages/runtime-api/src/response-labels';
import {managementText} from '../packages/runtime-api/src/management-values';
import {loadCertifiedDemoProject} from '../packages/runtime-api/src/demo-project';
import {boqProgrammeLinks} from '../packages/runtime-api/src/boq-programme-links';
import {moduleForProject} from '../packages/runtime-api/src/project-projections';
const script=cmengUatHtml().match(/<script>([\s\S]*?)<\/script>/)![1]!;
const ast=createSourceFile('served-browser.js',script,ScriptTarget.Latest,true);
const functions=(names:string[])=>names.map(name=>{const node=ast.statements.filter(isFunctionDeclaration).find(n=>n.name?.text===name);assert.ok(node,name+' exists in assembled browser');return node.getText(ast)}).join('\n');
for(let sample=0;sample<10;sample++)test('Round two full domains and exact source totals '+sample,()=>{
 const n=170+sample,rows=Array.from({length:n},(_,i)=>({activityId:'A'+i,activityType:'task',status:'not_started',criticality:'noncritical',plot:null,location:'Plot '+i}));
 const classified=rows.map((r,i)=>({...r,plot:'Plot '+i}));
 const view=activityRegisterView({rows,scopeClassification:{rows:classified},projectionKey:'activity_analytics'});
 const root={key:'activity-review',legacyKey:'activity-analytics',data:view};
 const projected:any=pageProjectResponse(root,'/api/projects/P/schedule/modules/activity-analytics');
 assert.equal(projected.data.activitySummary.filterOptions.plot.length,n,'all source plot values survive scope and transport');
 assert.equal(projected.data.activitySummary.filterOptions.location.length,n,'location choices do not come from the preview');
 assert.equal(projected.data.rows.length,50,'no second paging of the approved activity first page');
 const filtered=activityRegisterPage(classified,new URLSearchParams('plot=Plot+'+(n-1)));
 assert.equal(filtered.matchingCount,1);assert.equal(filtered.rows[0].activityId,'A'+(n-1));
 const register={key:'test',data:{rows:Array.from({length:227+sample},(_,i)=>({reference:'RFI-'+i,description:'Evidence'}))}};
 const response:any=pageProjectResponse(register,'/api/projects/P/delivery/modules/test');
 const context:any={currentModuleResult:response,responsePopulationRoot:null,responsePopulationIndex:new WeakMap(),responseRowPopulationIndex:new WeakMap()};
 const code=functions(['indexResponsePopulations','responseListPopulation']);
 const get=runInNewContext(code+';responseListPopulation',context);
 assert.equal(get(response.data.rows).total,227+sample);
 assert.equal(get(response.data.rows.slice(0,12)).total,227+sample,'copying preview rows retains the full source denominator');
 const next:any=recordDetailPage(register,'/data/rows',25);
 assert.equal(get(next.rows,{total:next.total,offset:next.offset}).total,227+sample,'paged drill-down uses returned server total');
 assert.equal(get(next.rows,{total:next.total,offset:next.offset}).offset,25);
 assert.equal(next.rows[0].reference,'RFI-25');
});
test('paging metadata never loses later source pointers after 180 entries',()=>{
 const facts=Object.fromEntries(Array.from({length:230},(_,i)=>['measure'+i,{value:i,state:'confirmed',sourceRefs:Array.from({length:90},(_,j)=>'document-'+i+':row:'+j)}]));
 const source:any={key:'master-dashboard',data:{projectFacts:facts,rows:Array.from({length:400},(_,i)=>({reference:'RFI-'+i}))}};
 const page:any=pageProjectResponse(source,'/api/projects/P/management/master-dashboard');
 assert.ok(page.responsePaging.tables.length>230);
 assert.equal(page.responsePaging.tables.find((t:any)=>t.pointer==='/data/rows').total,400);
 assert.equal(page.responsePaging.tables.find((t:any)=>t.pointer==='/data/projectFacts/measure229/sourceRefs').total,90);
 assert.equal(page.data.projectFacts.measure229.value,229);
 assert.equal((recordDetailPage(source,'/data/projectFacts/measure229/sourceRefs',75) as any).rows.length,15);
});
for(let sample=0;sample<10;sample++)test('BOQ item references and WBS scope relationships reach shared projections '+sample,()=>{
 const state=loadCertifiedDemoProject('R2-WBS-'+randomUUID()),model=state.schedules.at(-1)!.revision.model,q=state.quantities!;
 const wbs=model.wbs[0]!;wbs.code='CODE-'+sample;
 q.allocations=[];q.items=q.items.map((r,i)=>({...r,quantityItemId:'boqitem_'+sample+'_'+i,itemNumber:'SOURCE-'+sample+'.'+i,section:wbs.code!}));
 state.version++;
 const before=JSON.stringify(q),links=boqProgrammeLinks(state,model);
 assert.equal(links.coveragePercent,100);assert.equal(links.linkedItemCount,q.items.length);assert.equal(links.approvedAllocatedItemCount,0,'source scope is never promoted to approved allocation');
 assert.ok(links.rows.every((r:any)=>r.activityIds.length>0));
 const labels=projectSourceLabels(state);assert.equal(labels[q.items[0]!.quantityItemId],q.items[0]!.itemNumber);
 const selected=responseSourceLabels(labels,{sentence:'Linked '+q.items[0]!.quantityItemId+'; quantity remains source-owned'});
 const render=runInNewContext(functions(['readerReference'])+';readerReference',{currentModuleResult:{data:{sourceLabels:selected}}});
 assert.equal(render('Linked '+q.items[0]!.quantityItemId+'; quantity remains source-owned'),'Linked '+q.items[0]!.itemNumber+'; quantity remains source-owned');
 const result:any=moduleForProject(state.projectId,'quantity-scurve');
 assert.equal(result.data.itemLinkCoveragePercent,100);assert.equal(result.data.programmeMapping.itemLinkCoveragePercent,100);
 assert.equal(result.data.approvedAllocationCoveragePercent,0,'automatic planning scenarios do not create approved allocations');
 assert.equal(JSON.stringify(q),before,'reading WBS links does not alter stored measurements or allocations');
});
test('reader-facing due labels and partial timestamp suffix preserve the actual date',()=>{
 assert.equal(managementText('Status: Open; due=Sep 12, 2026'),'Status: Open; Due: Sep 12, 2026');
 assert.equal(managementText('2026-09-12T17:00:00Z'),'Sep 12, 2026');
 assert.equal(managementText('Sep 12, 2026T17:00:00'),'Sep 12, 2026 · 17:00');
 assert.doesNotMatch(managementText('due=2026-09-12T17:00:00.123Z; quantity=4.123456'),/due=|T17:|2026-09-12|\.\d{5,}/);
});
