import {createHash,randomUUID} from 'node:crypto';
import {mkdir,readFile,writeFile,rename,readdir,stat,rm} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import type {AnalysisResult,AskSession,SavedView} from '../../project-ask/src/types';
import {AskError,assertSameScope} from '../../project-ask/src/catalogue';
export const askHash=(v:unknown)=>createHash('sha256').update(JSON.stringify(v)).digest('hex');
export interface ReferenceFile {schemaVersion:1;id:string;projectId:string;workspaceId:string;ownerId:string;filename:string;hash:string;createdAt:string;state:'reference_only';reading:string;pages:{page:number;text:string;method:string}[]}
export interface Conversation {id:string;projectId:string;workspaceId:string;ownerId:string;analysisIds:string[];updatedAt:string}
/** Ask AI persistence is separate from governed project state. Each immutable result
 * is its own file; a follow-up cannot rewrite or promote source evidence. */
export class AskStore {
  constructor(private root=join(process.env.CMENG_DATA_DIR??process.env.RAILWAY_VOLUME_MOUNT_PATH??join(tmpdir(),'cmeng-ask-'+process.pid),'ask-ai')){}
  private directory(projectId:string,workspaceId:string){return join(this.root,askHash([workspaceId,projectId]));}
  private path(projectId:string,workspaceId:string,kind:string,id:string){if(!/^[a-zA-Z0-9_-]{1,100}$/.test(id))throw new AskError(404,'item_not_found','This saved item is not available.');return join(this.directory(projectId,workspaceId),kind,id+'.json');}
  private async write(path:string,value:unknown){await mkdir(join(path,'..'),{recursive:true,mode:0o700});const temporary=path+'.'+randomUUID()+'.tmp';try{await writeFile(temporary,JSON.stringify(value),{mode:0o600});await rename(temporary,path);}catch(error){await rm(temporary,{force:true}).catch(()=>{});throw error;}}
  private async read<T>(path:string):Promise<T>{try{const info=await stat(path);if(info.size>128*1024*1024)throw new Error();return JSON.parse(await readFile(path,'utf8')) as T;}catch{throw new AskError(404,'item_not_found','This saved item is not available.');}}
  async result(id:string,projectId:string,user:AskSession){const result=await this.read<AnalysisResult>(this.path(projectId,user.workspaceId,'results',id));assertSameScope(result.scope,user,projectId);return result;}
  async saveResult(result:AnalysisResult,user:AskSession){assertSameScope(result.scope,user,result.scope.projectId);await this.write(this.path(result.scope.projectId,user.workspaceId,'results',result.id),result);const path=this.path(result.scope.projectId,user.workspaceId,'conversations',result.conversationId);let conversation:Conversation;try{conversation=await this.conversation(result.conversationId,result.scope.projectId,user);}catch(e){if(!(e instanceof AskError)||e.status!==404)throw e;conversation={id:result.conversationId,projectId:result.scope.projectId,workspaceId:user.workspaceId,ownerId:user.userId,analysisIds:[],updatedAt:result.createdAt};}conversation.analysisIds.push(result.id);conversation.analysisIds=conversation.analysisIds.slice(-100);conversation.updatedAt=result.createdAt;await this.write(path,conversation);}
  async conversation(id:string,projectId:string,user:AskSession){const c=await this.read<Conversation>(this.path(projectId,user.workspaceId,'conversations',id));if(c.ownerId!==user.userId||c.workspaceId!==user.workspaceId||c.projectId!==projectId)throw new AskError(404,'conversation_not_found','This conversation is not available in the selected project.');return c;}
  async saveReference(reference:ReferenceFile,user:AskSession){if(reference.ownerId!==user.userId||reference.workspaceId!==user.workspaceId)throw new AskError(403,'reference_not_authorized','Reference access denied.');await this.write(this.path(reference.projectId,user.workspaceId,'references',reference.id),reference);}
  async reference(id:string,projectId:string,user:AskSession){const f=await this.read<ReferenceFile>(this.path(projectId,user.workspaceId,'references',id));if(f.ownerId!==user.userId||f.projectId!==projectId||f.workspaceId!==user.workspaceId)throw new AskError(404,'reference_not_found','This reference is not available in the selected project and session.');return f;}
  async saveView(view:SavedView,user:AskSession){if(view.ownerId!==user.userId||view.workspaceId!==user.workspaceId)throw new AskError(403,'publish_not_authorized','This view belongs to a different session.');if(view.plan.attachmentIds.length)throw new AskError(422,'reference_view_not_supported','A live view must use governed project authorities. Remove private reference attachments before saving.');await this.write(this.path(view.projectId,user.workspaceId,'views',view.id),view);}
  async views(projectId:string,user:AskSession){const directory=join(this.directory(projectId,user.workspaceId),'views');const names=await readdir(directory).catch(()=>[]);const result:SavedView[]=[];for(const name of names.filter(n=>n.endsWith('.json'))){const view=await this.read<SavedView>(join(directory,name));if(view.projectId===projectId&&view.workspaceId===user.workspaceId&&(view.ownerId===user.userId||view.visibility==='project'))result.push(view);}return result;}
  async view(id:string,projectId:string,user:AskSession){const v=(await this.views(projectId,user)).find(v=>v.id===id);if(!v)throw new AskError(404,'view_not_found','This view is not available.');return v;}
}
