export const systemReviewStyles=String.raw`
.nav-review-totals{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-bottom:10px;font-size:10px}.nav-review-totals div{padding:9px;background:#f1f5fa;border-radius:7px}.nav-review-totals b{display:block;font-size:18px;color:#284967}.position-verdict{border:1px solid #cfdae7;border-left:5px solid #b57922;border-radius:8px;padding:18px 22px;margin:0 0 18px;background:#fff}.position-verdict.red{border-left-color:#b4483e}.position-verdict.green{border-left-color:#2c7a57}.position-verdict.unknown{border-left-color:#7c8998}.position-verdict h4{margin:0 0 8px;font-size:19px}.position-verdict p{margin:6px 0}.position-verdict small{color:#566c81}.position-verdict details{margin-top:9px;font-size:12px}.nav-counts{display:flex;gap:4px;flex-wrap:wrap;justify-content:flex-end}.nav-counts .nav-count{font-size:9px;padding:2px 4px}.source-scope-summary{font-size:12px;margin-bottom:18px;padding:12px 16px;background:#f1f5fa;border-radius:7px}.source-scope-summary summary{cursor:pointer;font-weight:650}.source-quality-counts{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.source-quality-counts div{padding:16px;background:#f4f7fb;border:1px solid #dce5ef;border-radius:8px}.source-quality-counts b{display:block;font-size:25px}.decision-list{display:grid;gap:10px}.decision-list article{padding:15px;border:1px solid #dce5ef;border-radius:8px}.decision-list p{margin:5px 0}.decision-list small{color:#536c85}.future-register-note{margin:8px 0}.single-axis-caption{font-size:14px;font-weight:650;margin:18px 0 0}
`;
export const systemReviewScript=String.raw`
function renderPositionVerdict(data){
  const v=data?.positionVerdict;if(!v)return '';
  return '<section class="position-verdict '+escapeHtml(v.rag)+'" aria-label="Position verdict"><h4>'+escapeHtml(v.label)+'</h4><p>'+escapeHtml(v.text)+'</p><small><b>Next action:</b> '+escapeHtml(v.nextAction)+' <b>Action owner:</b> '+escapeHtml(v.owner)+'</small><details><summary>How to read the status</summary><p>'+escapeHtml(v.basis)+'</p></details></section>';
}
function renderRegisterScope(data){
  const contract=data?.reportingContract;if(!contract)return '';
  const populations=Object.values(contract.populations||{}).filter(p=>!['activity','execution_activity','series_point','currency_position','resource','assignment','programme_window'].includes(p.entity)&&!p.dateBasis?.startsWith('Full retained source register')&&!p.dateBasis?.startsWith('Source records after')&&!p.dateBasis?.startsWith('Source records without'));
  if(!populations.length)return '';
  const unique=[...new Map(populations.map(p=>[p.populationId,p])).values()];
  const row=p=>{const exclusions=p.exclusions||[],future=exclusions.filter(e=>e.reason==='after_data_date'),undated=exclusions.filter(e=>/date_missing|date_invalid/.test(e.reason));return '<tr><td>'+escapeHtml(p.name)+'</td><td>'+fmt(p.denominator)+' / '+fmt(p.sourceCount)+'</td><td>'+fmt(future.length)+'</td><td>'+fmt(undated.length)+'</td><td>'+escapeHtml(p.dateBasis)+'</td></tr>'};
  const exclusions=unique.map(p=>({p,future:(p.exclusions||[]).filter(e=>e.reason==='after_data_date').length,undated:(p.exclusions||[]).filter(e=>/date_missing|date_invalid/.test(e.reason)).length})).filter(r=>r.future||r.undated);
  const disclosure='<p class="future-register-note">'+(exclusions.length?exclusions.map(r=>escapeHtml(r.p.name)+': '+fmt(r.future)+' future, '+fmt(r.undated)+' undated / invalid').join(' · '):'No future or undated exclusions in the reported populations; review the individual date bases.')+'</p>';
  return disclosure+'<details class="source-scope-summary"><summary>Register date scope · '+planningShortDate(contract.dataDateIso)+' · future and undated records disclosed</summary><p>Counts are per population and may overlap. Future plan dates stay visible as plans; future actual events do not enter the current position. A zero means no exclusions on the stated basis, not that every field has a date.</p><div class="table-wrap"><table><thead><tr><th>Register</th><th>Included / source</th><th>Future excluded</th><th>Date missing / invalid</th><th>Date basis</th></tr></thead><tbody>'+unique.map(row).join('')+'</tbody></table></div></details>';
}
function renderSourceQuality(data){
  const rows=(items)=>items.length?'<div class="table-wrap"><table><thead><tr><th>Finding / source</th><th>Next action</th><th>Owner</th><th>Affected pages</th></tr></thead><tbody>'+items.map(i=>'<tr><td><b>'+escapeHtml(i.summary)+'</b><p>'+escapeHtml(i.detail)+'</p><small>'+escapeHtml((i.sourceRefs||[]).join(' · '))+'</small></td><td>'+escapeHtml(i.action)+'</td><td>'+escapeHtml(i.owner)+'</td><td>'+i.moduleKeys.map(k=>managementModuleLink(k,names[k]||k)).join(' ')+'</td></tr>').join('')+'</tbody></table></div>':'<p>None identified in the listed checks.</p>';
  return '<section class="source-quality-page"><p>'+escapeHtml(data.scope)+'</p><div class="source-quality-counts">'+[['Source issues',data.sourceIssues],['System failures',data.systemFailures],['Reviews / approvals',data.reviewActions],['Pending checks',data.pendingChecks]].map(([label,items])=>'<div>'+label+'<b>'+fmt(items?.length||0)+'</b></div>').join('')+'</div>'+managementPanel('System failures','Failed calculation or consistency checks belong to CMeng.',rows(data.systemFailures||[]))+managementPanel('Source quality and information requests','Missing, unread, conflicting and unlinked information keeps its own action and source.',rows(data.sourceIssues||[]))+experienceDisclosure('Review and approval actions',rows(data.reviewActions||[]),fmt(data.reviewActions?.length||0)+' findings')+experienceDisclosure('Cross-page value checks',basisTable(['Measure','Result','Page values'],(data.pageValueChecks||[]).map(c=>[c.metric,humanizeKey(c.state),c.values.map(v=>(names[v.page]||v.page)+': '+(typeof v.value==='object'?JSON.stringify(v.value).slice(0,200):v.value)).join(' · ')])),'All defined consumers compared')+experienceDisclosure('Verification coverage',rows(data.pendingChecks||[])+(data.coverage||[]).map(r=>'<details><summary>'+escapeHtml(names[r.key]||r.key)+' · '+escapeHtml(humanizeKey(r.state))+' · '+fmt(r.checks.length)+' checks</summary>'+basisTable(['Metric','Expected','Actual','Result'],r.checks.map(c=>[c.metric,JSON.stringify(c.expected),JSON.stringify(c.actual),c.passed?'Passed':'Failed']))+'</details>').join(''),'Exact checks and remaining scope')+experienceDisclosure('Source document inventory',basisTable(['Document','Type','Basis','Uploaded'],(data.documents||[]).map(d=>[d.name,humanizeKey(d.type),humanizeKey(d.state),formatDocumentTime(d.uploadedAt)])),fmt(data.documents?.length||0)+' documents')+'</section>';
}
function renderDashboardDecisions(data){
  const decisions=data.decisions||[];
  const body=decisions.length?'<div class="decision-list">'+decisions.slice(0,6).map(d=>'<article><b>'+escapeHtml(d.title||d.label||d.action||d.description)+'</b><small>Owner: '+escapeHtml(d.accountableOwner||d.owner||'Assignment needed')+' · Due: '+escapeHtml((d.dueDate||d.dueIso)?planningShortDate(d.dueDate||d.dueIso):'Date needed')+'</small><div>'+managementModuleLink(d.owningModule||'command-center','Open decision basis')+'</div></article>').join('')+'</div>':'<p>No source-backed decision has been recorded. Assign the outstanding evidence and operational actions below.</p>';
  return managementPanel('Decisions required','Priority decisions use the same records as Command Center. Missing assignments are explicit.',body+(decisions.length>6?managementModuleLink('command-center','All '+decisions.length+' decisions'):''),true);
}
function renderDashboardExceptions(data){
  const actions=data.operationalReporting?.actions||[];
  const table=rows=>basisTable(['Record','Priority','Age at DD','Overdue','Owner','Due','Action'],rows.map(r=>[r.recordId,r.priority,r.ageDays==null?'Raised date needed':r.ageDays+' d',r.overdueDays==null?'Due date needed':r.overdueDays+' d',r.owner||'Assign owner',r.dueIso?planningShortDate(r.dueIso):'Set due date',r.action]));
  return managementPanel('Delivery exceptions requiring action','Critical severity first, then overdue days and age at the Data Date. Missing owner or due date is an assignment task.',actions.length?table(actions.slice(0,5))+experienceDisclosure('All '+fmt(actions.length)+' action records',table(actions),'Complete NCR and RFI exceptions'):'<p>No confirmed open NCR or overdue RFI exceptions are present in the dated source subset.</p>',true);
}
function renderDashboardTrend(data){
  const rows=data.trend?.points||data.trend?.rows||data.trend?.revisions||[];
  if(!rows.length)return managementPanel('Completion trend','Dated revision history','<p>At least two dated revisions are needed to establish a trend.</p>');
  return managementPanel('How submitted completion changed','Revision dates and submitted finish dates; calendar recalculation is a separate comparison.',planningDateTrend(rows.map(r=>({...r,dateIso:r.dataDateIso||r.dateIso})),[{key:'sourceForecastCompletionIso',label:'Submitted completion',color:'#4276aa'}]));
}
`;
