import {createHash,randomBytes,randomUUID,verify} from 'node:crypto';
import {readFileSync,mkdirSync,writeFileSync,renameSync,openSync,closeSync,fsyncSync,appendFileSync,existsSync} from 'node:fs';
import {join} from 'node:path';
import type {IncomingMessage} from 'node:http';
import type {ExternalClient} from './types';
import {customerLimits,auditLimits,domains,fail,type ExternalPolicy,type ExternalUser,type Connection,type Limits,type Profile,type AnalysisSession} from './types';
export const digest=(v:unknown)=>createHash('sha256').update(typeof v==='string'?v:JSON.stringify(v)).digest('hex');
export const secret=()=>randomBytes(32).toString('base64url');
type Token={hash:string;kind:'access'|'refresh';connectionId:string;resource:string;expiresAt:string};
type Usage={month:string;day:string;monthly:number;daily:number;times:number[];records:number};
interface ControlState {schemaVersion:1;connections:Connection[];tokens:Token[];usage:Record<string,Usage>;projectDisabled:Record<string,boolean>;ownerSessions?:{hash:string;userId:string;expiresAt:string}[];usedActivations?:string[];registeredClients?:ExternalClient[]}
export class ExternalAccess {
  private file:string;private state:ControlState;
  constructor(readonly root:string,readonly policy:()=>ExternalPolicy|null,readonly now=()=>Date.now()){
    mkdirSync(root,{recursive:true,mode:0o700});this.file=join(root,'connections.json');
    this.state=existsSync(this.file)?JSON.parse(readFileSync(this.file,'utf8')):{schemaVersion:1,connections:[],tokens:[],usage:{},projectDisabled:{}};
    if(this.state.schemaVersion!==1||!Array.isArray(this.state.connections)||!Array.isArray(this.state.tokens))throw Error('EXTERNAL_CONTROL_STATE_INVALID');
  }
  private commit(next:ControlState){const tmp=this.file+'.'+randomUUID()+'.tmp';writeFileSync(tmp,JSON.stringify(next),{mode:0o600});const fd=openSync(tmp,'r');try{fsyncSync(fd)}finally{closeSync(fd)}renameSync(tmp,this.file);const dir=openSync(this.root,'r');try{fsyncSync(dir)}finally{closeSync(dir)}this.state=next;}
  configured(requireEnabled=true){const p=this.policy();if(!p||requireEnabled&&!p.enabled)fail(503,'external_access_disabled','External AI Access is not enabled for this installation.');if(p!.schemaVersion!==1||(!p!.identity?.publicKeyPem&&!p!.ownerActivation)||!p!.workspaceId||!p!.publicOrigin||!Array.isArray(p!.users)||!Array.isArray(p!.clients)||!p!.projects)fail(503,'identity_not_configured','External AI Access has not been configured.');const u=new URL(p!.publicOrigin);if(u.origin!==p!.publicOrigin||u.protocol!=='https:'&&!['127.0.0.1','localhost'].includes(u.hostname))fail(503,'origin_invalid','External AI Access requires its configured secure origin.');return p!;}
  activateOwner(value:unknown){
    const p=this.configured(false),activation=p.ownerActivation;
    if(typeof value!=='string'||!activation||Date.parse(activation.expiresAt)<=this.now()||digest(value)!==activation.hash||this.state.usedActivations?.includes(activation.hash))fail(401,'activation_invalid','This private activation link is invalid, expired or already used.');
    const user=this.user(activation!.userId,p.workspaceId),next=structuredClone(this.state),token='cmeng_owner_'+secret();
    next.ownerSessions=(next.ownerSessions??[]).filter(s=>Date.parse(s.expiresAt)>this.now()&&s.userId!==user.id);
    next.ownerSessions.push({hash:digest(token),userId:user.id,expiresAt:new Date(this.now()+7*86400000).toISOString()});
    (next.usedActivations??=[]).push(activation!.hash);this.commit(next);this.audit(null,'owner_connection_activated',null,[],0,'allowed',user.id);return token;
  }
  clients(){return [...this.configured().clients,...this.state.registeredClients??[]];}
  registerClient(name:unknown,redirects:unknown){
    const p=this.configured();if(typeof name!=='string'||!name.trim()||name.length>100||!Array.isArray(redirects)||!redirects.length||redirects.length>4||redirects.some(r=>{try{const u=new URL(r);return typeof r!=='string'||r.length>1024||u.protocol!=='https:'||!!u.username||!!u.password||!!u.hash||!(p.registrationRedirectOrigins??[]).includes(u.origin);}catch{return true;}}))fail(400,'invalid_client_metadata','Use an approved external assistant callback address.');
    const prior=this.clients().find(c=>JSON.stringify(c.redirectUris)===JSON.stringify(redirects)&&c.name===name);if(prior)return prior;
    const next=structuredClone(this.state);if((next.registeredClients??[]).length>=100)fail(429,'registration_limit','The external client registration limit has been reached.');const client={id:'cmeng_client_'+secret(),name:name as string,redirectUris:redirects as string[]};(next.registeredClients??=[]).push(client);this.commit(next);return client;
  }
  user(id:string,workspaceId:string){const p=this.configured(false),u=p.users.find(u=>u.id===id&&u.workspaceId===workspaceId&&u.enabled);if(!u||workspaceId!==p.workspaceId)fail(403,'access_denied','This connection is not authorized.');return u!;}
  identity(req:IncomingMessage):ExternalUser{const p=this.configured(false),cookies=(req.headers.cookie??'').split(/;\s*/);const owner=cookies.find(v=>v.startsWith('cmeng_external_owner='))?.slice(21);if(owner){const s=this.state.ownerSessions?.find(s=>s.hash===digest(owner)&&Date.parse(s.expiresAt)>this.now());if(s)return this.user(s.userId,p.workspaceId);}const name=p.identity.cookieName??'cmeng_identity';if(!/^[a-zA-Z0-9_-]+$/.test(name))fail(503,'identity_configuration_invalid','Identity configuration requires review.');const token=cookies.find(v=>v.startsWith(name+'='))?.slice(name.length+1);if(!token||token.length>16384)fail(401,'verified_identity_required','Open your private activation link in this browser before managing external connections.');try{const parts=token!.split('.');if(parts.length!==3)throw Error();const [h,b,s]=parts as [string,string,string],header=JSON.parse(Buffer.from(h,'base64url').toString()),claims=JSON.parse(Buffer.from(b,'base64url').toString());if(header.alg!=='RS256'||header.crit||!verify('RSA-SHA256',Buffer.from(h+'.'+b),p.identity.publicKeyPem,Buffer.from(s,'base64url'))||claims.iss!==p.identity.issuer||claims.aud!==p.identity.audience||typeof claims.sub!=='string'||typeof claims.exp!=='number'||claims.exp*1000<=this.now()||claims.nbf&&claims.nbf*1000>this.now()||claims.workspaceId!==p.workspaceId)throw Error();return this.user(claims.sub,claims.workspaceId);}catch{return fail(401,'verified_identity_required','The CMeng identity session is missing, expired or invalid.');}}
  limits(profile:Profile):Limits{const p=this.configured(),base=profile==='audit'?auditLimits:customerLimits,result={...base,...p.limits?.[profile]};for(const [key,v]of Object.entries(result))if(!Number.isSafeInteger(v)||v<1||v>(key.endsWith('Bytes')?134217728:10000000))fail(503,'limit_configuration_invalid','External access limits require review: '+key);if(result.maxRank>result.recordsPerResponse||result.recordsPerResponse>result.recordsPerSession)fail(503,'limit_configuration_invalid','Rank and response limits must fit the analysis session.');return result;}
  project(user:ExternalUser,projectId:string,requested:string[]){const p=this.configured(),rule=p.projects[projectId],allowed=user.projects[projectId];if(!rule?.enabled||this.state.projectDisabled[projectId]||!allowed||!requested.every(d=>domains.includes(d as any)&&allowed.includes(d as any)&&rule.domains.includes(d as any)))fail(403,'project_or_domain_denied','This project or requested domain is not authorized for external access.');}
  create(user:ExternalUser,input:{clientId:string;profile:Profile;projects:Record<string,string[]>}){if(!this.clients().some(c=>c.id===input.clientId))fail(400,'client_not_registered','Select a configured external connection.');if(!['customer','audit'].includes(input.profile)||input.profile==='audit'&&!user.allowAudit)fail(403,'profile_denied','Developer/Audit access is restricted to explicitly authorized users.');const ids=Object.keys(input.projects??{});if(!ids.length||ids.length>100)fail(400,'project_required','Select between one and 100 permitted projects.');for(const id of ids){if(!Array.isArray(input.projects[id])||!input.projects[id]!.length)fail(400,'domains_required','Select permitted domains.');this.project(user,id,input.projects[id]!);}
    const next=structuredClone(this.state);next.connections=next.connections.filter(c=>Date.parse(c.expiresAt)>this.now());if(next.connections.length>=2000||next.connections.filter(c=>c.userId===user.id&&!c.revokedAt).length>=30)fail(429,'connection_limit','Revoke an unused connection before creating another.');const c:Connection={id:randomUUID(),userId:user.id,workspaceId:user.workspaceId,clientId:input.clientId,profile:input.profile,projects:structuredClone(input.projects) as Connection['projects'],createdAt:new Date(this.now()).toISOString(),expiresAt:new Date(this.now()+this.limits(input.profile).connectionSeconds*1000).toISOString(),revokedAt:null,lastUsedAt:null};next.connections.push(c);this.commit(next);this.audit(c,'connection_created',null,[],0,'allowed');return c;}
  connection(id:string){const c=this.state.connections.find(c=>c.id===id);if(!c||c.revokedAt||Date.parse(c.expiresAt)<=this.now())fail(401,'connection_invalid','The external connection is expired or revoked.');const u=this.user(c!.userId,c!.workspaceId);if(c!.profile==='audit'&&!u.allowAudit)fail(403,'profile_denied','Developer/Audit access is no longer authorized.');return {connection:c!,user:u};}
  authorize(token:string,projectId?:string,required:string[]=[]){const p=this.configured(),t=this.state.tokens.find(t=>t.hash===digest(token)&&t.kind==='access');if(!/^cmeng_ext_[A-Za-z0-9_-]{43}$/.test(token)||!t||t.resource!==p.publicOrigin+'/external-ai/mcp'||Date.parse(t.expiresAt)<=this.now())fail(401,'invalid_token','The external access token is missing, expired or invalid.');const v=this.connection(t!.connectionId);if(projectId){this.project(v.user,projectId,required);if(!v.connection.projects[projectId]||!required.every(d=>v.connection.projects[projectId]!.includes(d as any)))fail(403,'connection_scope_denied','This connection does not include the requested project or domains.');}return v;}
  issue(connectionId:string,resource:string){const {connection:c}=this.connection(connectionId),p=this.configured();if(resource!==p.publicOrigin+'/external-ai/mcp')fail(400,'invalid_target','The resource must identify this CMeng external gateway.');const access='cmeng_ext_'+secret(),refresh='cmeng_refresh_'+secret(),next=structuredClone(this.state);next.tokens=next.tokens.filter(t=>Date.parse(t.expiresAt)>this.now());if(next.tokens.filter(t=>t.connectionId===c.id).length>=30)fail(429,'token_limit','Too many active tokens for this connection.');const accessExpiry=Math.min(this.now()+900000,Date.parse(c.expiresAt));next.tokens.push({hash:digest(access),kind:'access',connectionId:c.id,resource,expiresAt:new Date(accessExpiry).toISOString()},{hash:digest(refresh),kind:'refresh',connectionId:c.id,resource,expiresAt:c.expiresAt});this.commit(next);return {access_token:access,refresh_token:refresh,token_type:'Bearer',expires_in:Math.floor((accessExpiry-this.now())/1000),scope:'cmeng:read'};}
  refresh(token:string,clientId:string,resource:string){const t=this.state.tokens.find(t=>t.kind==='refresh'&&t.hash===digest(token));if(!t||Date.parse(t.expiresAt)<=this.now()||t.resource!==resource)fail(401,'invalid_grant','The refresh token is not valid.');const {connection:c}=this.connection(t!.connectionId);if(c.clientId!==clientId)fail(401,'invalid_grant','The refresh token is not valid.');const next=structuredClone(this.state);next.tokens=next.tokens.filter(v=>v.connectionId!==c.id);this.commit(next);return this.issue(c.id,resource);}
  list(user:ExternalUser){return this.state.connections.filter(c=>c.workspaceId===user.workspaceId&&(user.externalAdmin||c.userId===user.id)).map(c=>({...c,status:c.revokedAt?'revoked':Date.parse(c.expiresAt)<=this.now()?'expired':'active'}));}
  revokeToken(token:string,clientId:string){const found=this.state.tokens.find(t=>t.hash===digest(token)),c=found&&this.state.connections.find(c=>c.id===found.connectionId&&c.clientId===clientId);if(!c)return;const next=structuredClone(this.state);next.tokens=next.tokens.filter(t=>t.connectionId!==c.id);next.connections.find(x=>x.id===c.id)!.revokedAt=new Date(this.now()).toISOString();this.commit(next);this.audit(c,'connection_revoked',null,[],0,'allowed');}
  revoke(user:ExternalUser,id:string){const next=structuredClone(this.state),c=next.connections.find(c=>c.id===id&&c.workspaceId===user.workspaceId&&(user.externalAdmin||c.userId===user.id));if(!c)fail(404,'connection_not_found','This connection is not available.');c!.revokedAt=new Date(this.now()).toISOString();next.tokens=next.tokens.filter(t=>t.connectionId!==id);this.commit(next);this.audit(c!,'connection_revoked',null,[],0,'allowed');}
  disableProject(user:ExternalUser,id:string,disabled:boolean){if(!user.externalAdmin||!this.configured().projects[id])fail(403,'admin_required','Only a configured administrator can change project external access.');const next=structuredClone(this.state);next.projectDisabled[id]=disabled;this.commit(next);this.audit(null,disabled?'project_disabled':'project_enabled',id,[],0,'allowed',user.id);}
  projectEnabled(id:string){return this.configured().projects[id]?.enabled===true&&!this.state.projectDisabled[id];}
  consume(c:Connection,projectId:string|null,records=0,request=true){this.connection(c.id);const key=digest([c.workspaceId,c.userId,projectId??'capabilities']),next=structuredClone(this.state),today=new Date(this.now()).toISOString().slice(0,10),month=today.slice(0,7),limits=this.limits(c.profile);const u=next.usage[key]??={month,day:today,monthly:0,daily:0,times:[],records:0};if(u.month!==month){u.month=month;u.monthly=0;u.records=0;}if(u.day!==today){u.day=today;u.daily=0;}u.times=u.times.filter(t=>t>this.now()-60000);if(request&&(u.times.length>=limits.requestsPerMinute||u.daily>=limits.dailyRequests||u.monthly>=limits.monthlyRequests))fail(429,'query_limit','The configured external query allowance has been reached.');if(u.records+records>limits.recordsPerMonth)fail(429,'bulk_export_required','Cumulative record disclosure reached the configured limit. Use CMeng’s governed export for bulk project data.');if(request){u.times.push(this.now());u.daily++;u.monthly++;}u.records+=records;const stored=next.connections.find(x=>x.id===c.id);if(stored)stored.lastUsedAt=new Date(this.now()).toISOString();this.commit(next);}
  usage(user:ExternalUser){return Object.entries(this.state.usage).filter(([key])=>Object.keys(user.projects).some(id=>digest([user.workspaceId,user.id,id])===key)).map(([key,value])=>({scopeId:key,...value,times:undefined}));}
  audit(c:Connection|null,capability:string,projectId:string|null,accessedDomains:string[],records:number,outcome:string,userId?:string,analysisId?:string,projectVersion?:number){const event={at:new Date(this.now()).toISOString(),connectionId:c?.id??null,userId:c?.userId??userId??null,workspaceId:c?.workspaceId??null,projectId,analysisId:analysisId??null,projectVersion:projectVersion??null,capability,domains:accessedDomains,recordsReturned:records,outcome};appendFileSync(join(this.root,'audit-'+event.at.slice(0,10)+'.jsonl'),JSON.stringify(event)+'\n',{mode:0o600});}
  saveSession(session:AnalysisSession){const path=join(this.root,'sessions');mkdirSync(path,{recursive:true,mode:0o700});const bytes=JSON.stringify(session);if(Buffer.byteLength(bytes)>this.limits(this.connection(session.connectionId).connection.profile).sessionBytes)fail(413,'analysis_scope_too_large','This analysis exceeds the configured evidence budget. Narrow the objective or use a governed CMeng export.');const file=join(path,session.id+'.json'),tmp=file+'.'+randomUUID()+'.tmp';writeFileSync(tmp,bytes,{mode:0o600});renameSync(tmp,file);}
  session(id:string,c:Connection){if(!/^[0-9a-f-]{36}$/.test(id))fail(404,'analysis_not_found','This analysis is not available.');let s:AnalysisSession;try{s=JSON.parse(readFileSync(join(this.root,'sessions',id+'.json'),'utf8'));}catch{fail(404,'analysis_not_found','This analysis is not available.');}if(s!.connectionId!==c.id||s!.userId!==c.userId||s!.workspaceId!==c.workspaceId||Date.parse(s!.expiresAt)<=this.now())fail(404,'analysis_not_found','This analysis is not available or has expired.');return s!;}
}
export function filePolicy(path:string|undefined):()=>ExternalPolicy|null{return ()=>{if(!path)return null;try{return JSON.parse(readFileSync(path,'utf8'));}catch{fail(503,'access_policy_unavailable','External access policy could not be loaded. Access is closed.');}};}
