// Public capability metadata only. Parity with the live authority catalogue is checked in tests.
import type {AuthorityDescriptor} from "../../project-ask/src/types";
export const externalAuthorityMetadata:AuthorityDescriptor[]=[
  {
    "id": "project-diagnosis",
    "title": "Project diagnosis",
    "description": "Shared programme position, driving network, WBS pressure, revision changes and explicitly linked multi-domain evidence.",
    "module": "pmo-analysis",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "project diagnosis",
      "finish drivers",
      "why are we late"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score",
      "schedulePressure",
      "onDrivingNetwork",
      "wbs",
      "critical",
      "criticality",
      "floatRiskWatchlist",
      "missedPlannedStart",
      "finishOverdue",
      "scheduleDelayed",
      "startOverdueCalendarDays",
      "finishOverdueCalendarDays",
      "currentStartIso",
      "currentFinishIso",
      "finishVarianceDays",
      "independentTotalFloatHours",
      "schedulePressure",
      "onDrivingNetwork",
      "wbs"
    ],
    "historical": false
  },
  {
    "id": "critical-path",
    "title": "Critical activities",
    "description": "Calculated critical activities, or a clearly labelled source-float list when CPM is unavailable.",
    "module": "independent-forecast",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "critical path",
      "driving path"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score",
      "schedulePressure",
      "onDrivingNetwork",
      "wbs",
      "critical",
      "criticality",
      "floatRiskWatchlist",
      "missedPlannedStart",
      "finishOverdue",
      "scheduleDelayed",
      "startOverdueCalendarDays",
      "finishOverdueCalendarDays",
      "currentStartIso",
      "currentFinishIso",
      "finishVarianceDays",
      "independentTotalFloatHours"
    ],
    "historical": false
  },
  {
    "id": "boq",
    "title": "BOQ / Scope",
    "description": "Selected BOQ source quantities, item values and scope. No cross-currency sum.",
    "module": "boq",
    "domains": [
      "boq",
      "commercial"
    ],
    "concepts": [
      "boq",
      "scope",
      "cost driver",
      "cost distribution",
      "bill of quantities",
      "جدول الكميات"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "master-dashboard",
    "title": "Master Dashboard",
    "description": "Completion commitments, programme pressure and commercial position.",
    "module": "master-dashboard",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "kpi dashboard",
      "executive summary",
      "kpi",
      "key figures",
      "project status",
      "project position"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "command-center",
    "title": "Command Center",
    "description": "Delivery priorities, suggested follow-up and decisions awaiting assignment.",
    "module": "command-center",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "management action",
      "director",
      "meeting",
      "what killing",
      "urgent"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "master-control-programme",
    "title": "Master Control Programme",
    "description": "Controlled revisions, project structure, specialist positions and review history.",
    "module": "master-control-programme",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "programme control",
      "project history",
      "joined"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "source-quality",
    "title": "Actions required",
    "description": "Your pending confirmations, reviews and information requests in one place.",
    "module": "source-quality",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "missing evidence",
      "information gaps",
      "evidence gaps"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "pmo-analysis",
    "title": "Management Brief",
    "description": "Finish-date outlook, schedule pressure and decisions requiring management attention.",
    "module": "pmo-analysis",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "management brief",
      "executive brief"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "programme",
    "title": "Programme Review",
    "description": "Programme health, logic quality, float and finish dates.",
    "module": "schedule-analytics",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "programme",
      "schedule position",
      "data date",
      "reporting date",
      "program",
      "البرنامج",
      "تاريخ البيانات"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "activities",
    "title": "Activity Review",
    "description": "Activity finish movement, float and programme comparisons.",
    "module": "activity-analytics",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "activities",
      "activity",
      "critical activities",
      "انشطه"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score",
      "schedulePressure",
      "onDrivingNetwork",
      "wbs",
      "critical",
      "criticality",
      "floatRiskWatchlist",
      "missedPlannedStart",
      "finishOverdue",
      "scheduleDelayed",
      "startOverdueCalendarDays",
      "finishOverdueCalendarDays",
      "currentStartIso",
      "currentFinishIso",
      "finishVarianceDays",
      "independentTotalFloatHours"
    ],
    "historical": false
  },
  {
    "id": "lookahead",
    "title": "Look-Ahead",
    "description": "The next six weeks, readiness blockers and overdue work.",
    "module": "lookahead-schedule",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "lookahead",
      "look-ahead",
      "next week"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "programme-changes",
    "title": "Programme Changes",
    "description": "What changed between the latest controlled programme submissions.",
    "module": "schedule-change-report",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "changed",
      "change since",
      "previous update",
      "programme change"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "revision-history",
    "title": "Revision History",
    "description": "How progress, forecast finish and schedule pressure have moved over time.",
    "module": "revision-trend",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "history",
      "revisions",
      "revision",
      "joined",
      "تاريخ المشروع"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "milestones",
    "title": "Milestones",
    "description": "Milestone status, submitted float, due dates, baseline movement and required management review.",
    "module": "milestones",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "milestone",
      "المعالم"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "float",
    "title": "Near-Critical & Float Risk",
    "description": "Strict near-critical activities and the wider float-risk watchlist, kept separate and reconciled to the submitted source position.",
    "module": "near-critical",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "critical",
      "float",
      "worst",
      "حرج"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score",
      "schedulePressure",
      "onDrivingNetwork",
      "wbs",
      "critical",
      "criticality",
      "floatRiskWatchlist",
      "missedPlannedStart",
      "finishOverdue",
      "scheduleDelayed",
      "startOverdueCalendarDays",
      "finishOverdueCalendarDays",
      "currentStartIso",
      "currentFinishIso",
      "finishVarianceDays",
      "independentTotalFloatHours"
    ],
    "historical": false
  },
  {
    "id": "resources",
    "title": "Resources",
    "description": "Weekly demand, actual usage and available capacity by resource.",
    "module": "resource-utilization",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "resources",
      "labour",
      "labor",
      "manpower",
      "crew",
      "عماله"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "progress",
    "title": "Progress Status",
    "description": "Baseline, current schedule, physical, contractor-reported and certified progress kept separate.",
    "module": "progress-report",
    "domains": [
      "schedule",
      "boq"
    ],
    "concepts": [
      "current completion",
      "completion percentage",
      "progress",
      "behind",
      "slippage",
      "التقدم",
      "انجاز"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "variance",
    "title": "Variance Trend",
    "description": "Activity finish movement and schedule pressure across controlled programme revisions.",
    "module": "variance-trends",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "variance trend",
      "movement"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "progress-curve",
    "title": "Progress S-Curve",
    "description": "Derived baseline/current plans and schedule snapshot history on one time axis.",
    "module": "progress-scurve",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "progress curve",
      "s-curve",
      "s curve",
      "progress chart"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "quantities",
    "title": "Installed Quantities",
    "description": "BOQ and measured installations by unit; planned quantities require a defensible schedule mapping.",
    "module": "quantity-scurve",
    "domains": [
      "boq",
      "schedule"
    ],
    "concepts": [
      "installed",
      "installed quantity",
      "quantity progress",
      "quantities",
      "quantity completion",
      "كميات"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "wbs",
    "title": "Progress Breakdown",
    "description": "Current programme activity progress by WBS, WBS level, zone, spatial level, work front and CBS, with source coverage stated explicitly.",
    "module": "progress-breakdown",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "wbs",
      "by trade",
      "work breakdown"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "manhours",
    "title": "Man-Hour S-Curve",
    "description": "Planned, actual and forecast labor hours, with history coverage stated explicitly.",
    "module": "manhour-scurve",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "manhour",
      "man-hour",
      "man hour",
      "ساعات العمل"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "forecast-history",
    "title": "Completion History",
    "description": "How submitted finishes and calendar recalculations move across programme revisions.",
    "module": "forecast-history",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "completion history",
      "forecast history"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "forecast",
    "title": "Completion Forecast",
    "description": "Submitted completion, calendar recalculation and the productivity outlook, with each calculation basis and unresolved limit stated.",
    "module": "independent-forecast",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "forecast",
      "finish",
      "completion date",
      "cpm",
      "التوقع",
      "الانتهاء"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "challenge-contract",
    "title": "Challenge the Contract",
    "description": "Tests the submitted manpower plan and current schedule against project evidence and required milestones, then combines the gaps, consequences and actions.",
    "module": "challenge-contract",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "challenge the contract",
      "contract challenge"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "delay",
    "title": "Delay Event Register",
    "description": "Recorded delay events, affected activities and linked records for investigation. Causation requires supporting evidence.",
    "module": "delay-claims",
    "domains": [
      "claims",
      "schedule"
    ],
    "concepts": [
      "delay event",
      "delay claim",
      "تأخير"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "notices",
    "title": "Notice Compliance",
    "description": "Event dates, notice deadlines and issue dates checked against the applicable contract version.",
    "module": "notices-claims",
    "domains": [
      "claims"
    ],
    "concepts": [
      "notice",
      "claim notice",
      "اخطار"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "windows",
    "title": "Delay Windows",
    "description": "Revision-to-revision programme movement kept separate from causation and entitlement.",
    "module": "windows-analysis",
    "domains": [
      "claims",
      "schedule"
    ],
    "concepts": [
      "windows analysis",
      "concurrent",
      "causation",
      "time impact"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "eot",
    "title": "EOT Assessment",
    "description": "Time-impact evidence, entitlement assessment and dated EOT determinations, with unresolved overlap stated.",
    "module": "eot-assessment",
    "domains": [
      "claims",
      "schedule"
    ],
    "concepts": [
      "eot",
      "extension",
      "claims",
      "entitlement",
      "تمديد"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "commercial",
    "title": "Commercial Overview",
    "description": "Integrated contract value, change, payment, retention, bond, claim and time position by currency.",
    "module": "commercial-overview",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "commercial",
      "contract value",
      "cost exposure",
      "commercial kpi",
      "التجاري"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "evm",
    "title": "Cost Outlook",
    "description": "Original and current contract value, approved/pending change and claim exposure without cross-currency arithmetic.",
    "module": "cost-forecast",
    "domains": [
      "commercial"
    ],
    "concepts": [
      "cpi",
      "spi",
      "evm",
      "earned value",
      "cost performance",
      "ev",
      "pv",
      "ac",
      "مؤشر التكلفه"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "variations",
    "title": "Variations & Change",
    "description": "Approved and pending variation exposure with approval status and dates.",
    "module": "variations-change",
    "domains": [
      "commercial"
    ],
    "concepts": [
      "variation",
      "change order",
      "تغيير"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "payments",
    "title": "Payments",
    "description": "Interim certificates, certified value, payments, unpaid certified balance, retention and advance evidence.",
    "module": "payments",
    "domains": [
      "commercial"
    ],
    "concepts": [
      "paid",
      "payment",
      "certificate",
      "certified",
      "retention",
      "دفع",
      "مستخلص"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "cash",
    "title": "Cash Flow",
    "description": "Actual cash availability, certificate reconciliation and the future certificate plan.",
    "module": "cash-flow",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "cash",
      "cash flow",
      "التدفق النقدي"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "financial-claims",
    "title": "Financial Claims",
    "description": "Claimed and assessed money by currency, financial exposure and recovery status, linked to the supporting time and notice records.",
    "module": "commercial-claims-notices",
    "domains": [
      "commercial",
      "claims"
    ],
    "concepts": [
      "financial claim",
      "claimed amount",
      "money claim"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "contract",
    "title": "Contract Particulars & Bonds",
    "description": "Contract value, contractual completion, approved EOT and active security position.",
    "module": "contract-particulars-bonds",
    "domains": [
      "commercial",
      "claims"
    ],
    "concepts": [
      "contract particulars",
      "bonds",
      "insurance",
      "retention",
      "العقد",
      "ضمان"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "delivery-control",
    "title": "Delivery Control",
    "description": "Cross-package scope, supply, construction and handover exceptions.",
    "module": "delivery-control",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "delivery control"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "procurement",
    "title": "Procurement Packages",
    "description": "Required actions, delivery exposure and the package lifecycle.",
    "module": "procurement-packages",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "procurement",
      "package",
      "مشتريات",
      "توريد"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "materials",
    "title": "Material Tracking",
    "description": "Required, ordered, delivered, accepted and installed quantities by compatible unit.",
    "module": "material-tracking",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "material",
      "ordered",
      "delivered",
      "installation",
      "المواد",
      "تسليم"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "long-lead",
    "title": "Long Lead",
    "description": "Latest procurement actions using controlled programme need dates and evidenced lead times.",
    "module": "long-lead",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "long lead",
      "long-lead",
      "transformer",
      "lead time",
      "latest order"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "submittals",
    "title": "Submittals",
    "description": "Submission, review and approval position with revision control.",
    "module": "delivery-submittals",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "submittal",
      "approval",
      "review duration",
      "اعتماد"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "procurement-curves",
    "title": "Procurement S-Curves",
    "description": "Separate throughput, value, weighted progress, material and approval curves.",
    "module": "procurement-scurves",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "procurement curve",
      "value curve",
      "weighted procurement",
      "procurement progress"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "suppliers",
    "title": "Suppliers & Subcontractors",
    "description": "Linked package delivery and performance.",
    "module": "delivery-suppliers",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "supplier",
      "subcontractor",
      "مورد"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "design",
    "title": "RFI & Design",
    "description": "Required information, response dates and design blockers.",
    "module": "delivery-design",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "design",
      "rfi",
      "technical approval",
      "تصميم"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "disciplines",
    "title": "Discipline Progress",
    "description": "Existing programme progress by governed discipline and workfront links.",
    "module": "construction-discipline",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "discipline",
      "trade",
      "construction matrix",
      "mep"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "locations",
    "title": "Location / Floor / Zone",
    "description": "Workfront progress through the governed project location hierarchy.",
    "module": "construction-locations",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "floor",
      "location",
      "zone",
      "tower",
      "building",
      "طابق",
      "موقع"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "construction-readiness",
    "title": "Construction Readiness",
    "description": "Applicable workfront gates, confirmed blockers and unresolved prerequisites.",
    "module": "construction-readiness",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "construction readiness",
      "workfront",
      "جاهزيه التنفيذ"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "procurement-readiness",
    "title": "Procurement Readiness",
    "description": "Applicable package gates, quantities and programme need-date exposure.",
    "module": "procurement-readiness",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "procurement readiness",
      "جاهزيه التوريد"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "quality",
    "title": "Quality & Inspections",
    "description": "NCR, WIR, MIR, inspections, verification and rework.",
    "module": "delivery-quality",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "quality",
      "ncr",
      "inspection",
      "جوده"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "permits",
    "title": "Permits & Authorities",
    "description": "Issued permits, validity and workfront constraints.",
    "module": "delivery-permits",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "permit",
      "authority approval",
      "تصريح"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "hse",
    "title": "Construction HSE",
    "description": "Incidents, inspections and exposure-based safety rates.",
    "module": "delivery-hse",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "hse",
      "injury",
      "injuries",
      "safety",
      "frequency rate",
      "سلامه"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "commissioning",
    "title": "Testing & Commissioning",
    "description": "System tests, outcomes, retests and acceptance evidence.",
    "module": "delivery-commissioning",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "commissioning",
      "testing",
      "test pass",
      "تشغيل"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "assets",
    "title": "Asset & System Handover",
    "description": "Installation, commissioning, documentation and handover relationships.",
    "module": "delivery-assets",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "asset",
      "system handover",
      "اصول"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "closeout",
    "title": "Snag & Closeout",
    "description": "Outstanding construction work, rectification and verified closure.",
    "module": "delivery-closeout",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "snag",
      "closeout",
      "punch",
      "closure"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "spares",
    "title": "Spares & Special Tools",
    "description": "Required, delivered, accepted, stored and handed-over quantities.",
    "module": "delivery-spares",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "spare",
      "special tool",
      "قطع غيار"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "handover",
    "title": "Handover Readiness",
    "description": "Accepted requirements against a confirmed handover population.",
    "module": "handover-readiness",
    "domains": [
      "delivery"
    ],
    "concepts": [
      "handover",
      "accepted requirements",
      "تسليم نهائي"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "weather",
    "title": "Weather / Disruption Evidence",
    "description": "Recorded site disruption and links to the existing claims authority.",
    "module": "delivery-weather",
    "domains": [
      "delivery",
      "claims"
    ],
    "concepts": [
      "weather",
      "disruption",
      "طقس"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "risks",
    "title": "Delivery Risks",
    "description": "The governed project risk register viewed by delivery consequence.",
    "module": "delivery-risks",
    "domains": [
      "delivery",
      "claims"
    ],
    "concepts": [
      "risk",
      "what worry",
      "مخاطر"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "productivity",
    "title": "Productivity / Installation Rates",
    "description": "Existing source productivity calculation with explicit scope and activity links.",
    "module": "independent-forecast",
    "domains": [
      "schedule",
      "boq",
      "delivery",
      "commercial",
      "claims",
      "evidence"
    ],
    "concepts": [
      "productivity",
      "installation rate",
      "productivity weak",
      "انتاجيه"
    ],
    "fields": [
      "recordId",
      "reference",
      "description",
      "name",
      "itemNumber",
      "activityId",
      "wbsId",
      "discipline",
      "location",
      "floor",
      "zone",
      "supplier",
      "unit",
      "currency",
      "taxBasis",
      "status",
      "state",
      "amount",
      "required",
      "ordered",
      "delivered",
      "installed",
      "deliveryCoveragePercent",
      "totalFloatHours",
      "headroomCalendarDays",
      "programmeNeedDate",
      "percentComplete",
      "score"
    ],
    "historical": false
  },
  {
    "id": "phase-programmes",
    "title": "Phase Programme Positions",
    "description": "Separate adopted programme positions for each project phase; no automatic whole-project roll-up.",
    "module": "phase-programmes",
    "domains": [
      "schedule"
    ],
    "concepts": [
      "phase",
      "phases",
      "next phase"
    ],
    "fields": [
      "phaseId",
      "dataDate",
      "revisionId",
      "activityCount",
      "role",
      "authorityState"
    ],
    "historical": false
  }
];

const analyticFields=[
  'recordId','reference','description','name','itemNumber','activityId','wbsId','discipline','trade','system','packageCandidate','package','location','building','tower','floor','level','zone','area','sectionScope','chainage','supplier','unit','currency','taxBasis','status','state','amount','required','ordered','delivered','installed','deliveryCoveragePercent','totalFloatHours','headroomCalendarDays','programmeNeedDate','percentComplete','score','procurementPriority','longLeadCandidate','criticalScopeCandidate',
  'interfaceId','givingParty','receivingParty','requiredDeliverable','requiredDate','responsibleParty','affectedWorkfront','linkedActivity','linkedRfi','linkedSubmittal','linkedRisk',
  'scenarioId','type','possibleDaysRecovered','additionalResources','implementationDate','dimension','value','openIssueCount','domainCount','overdueCount','affectedActivityCount','worstOverdueDays'
];
externalAuthorityMetadata.push(
  {id:'accountability',title:'Accountability',description:'Who holds the largest concentration of open and overdue items across Project control domains, with full drill-back.',module:'cross-domain-accountability',domains:['schedule','delivery','claims','evidence'],concepts:['accountability','who is holding','who holds','who is delaying','who has most overdue','contractor performance','responsible party','open items by contractor'],fields:[...analyticFields],historical:false},
  {id:'recovery',title:'Recovery & Acceleration',description:'Evidence-based recovery scenarios with assumptions, local days recoverable, resources, cost limits, constraints and risk.',module:'recovery-acceleration',domains:['schedule','delivery','boq'],concepts:['recovery','acceleration','accelerate','recover days','additional crew','extra crew','additional shift','extra shift','resequence','re-sequence','expedite','recovery plan'],fields:[...analyticFields],historical:false},
  {id:'interfaces',title:'Interface Management',description:'Package, discipline, system and contractor interfaces that can constrain delivery.',module:'delivery-interfaces',domains:['delivery','schedule'],concepts:['interface','interfaces','interface register','package interface','discipline interface','system interface','contractor interface'],fields:[...analyticFields],historical:false}
);
const scheduleFields=['schedulePressure','onDrivingNetwork','wbs','critical','criticality','floatRiskWatchlist','missedPlannedStart','finishOverdue','scheduleDelayed','startOverdueCalendarDays','finishOverdueCalendarDays','currentStartIso','currentFinishIso','finishVarianceDays','independentTotalFloatHours'];
for(const item of externalAuthorityMetadata){
  if(item.fields.includes('recordId')){
    const scheduleSpecific=item.fields.some(field=>scheduleFields.includes(field));
    item.fields=[...analyticFields,...(scheduleSpecific?scheduleFields:[])];
  }
  if(item.id==='project-diagnosis'){
    item.title='Project position';
    item.concepts=['project position','finish drivers','why are we late'];
  }
}
