import {createHash} from 'node:crypto';
import type {IncomingMessage,ServerResponse} from 'node:http';
import {ExternalAccess,digest,secret} from './access';
import {ExternalIntelligenceService} from './service';
import {capabilities,domains,ExternalError,fail,type Capability,type Query,type ExternalUser} from './types';
import {readManagedAskSettings,saveManagedAskSettings,ownerOpenAiModels} from '../../project-ask/src/settings';

const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const descriptions:Record<Capability,string>={
  describe_capabilities:'Discover the permitted CMeng project analyses and fields. Does not retrieve project records.',
  get_project_state:'Check the live project version and reporting date before current-state analysis or a final report.',
  get_project_metric:'Retrieve a project metric, such as CPI or SPI, from CMeng calculations. No language model is called.',
  run_project_analysis:'Run a specific project question against CMeng calculations. Returns bounded facts, findings, coverage and trace references. Read all indicated batches before claiming a complete assessment.',
  get_ranked_result:'Return a complete requested rank, such as Top 20 BOQ cost drivers. Specify objective and optionally supported authority, ranking field, direction and limit.',
  get_related_records:'Retrieve explicit links for a record already represented in this analysis. Does not infer relationships or permit unrestricted traversal.',
  get_evidence_trace:'Inspect a trace ID from this analysis, including source references and exclusions.',
  search_evidence:'Search permitted evidence referenced by this analysis for specific terms. Returns bounded passages, not whole files.',
  get_analysis_batch:'Retrieve the next selected evidence batch using its exact continuation token. This is not raw database pagination.',
  check_analysis_freshness:'Check whether an analysis still matches the current project version before using its conclusions.'
};
export const externalTools=capabilities.map(name=>({name,title:name.split('_').join(' '),description:descriptions[name],annotations:{readOnlyHint:true,destructiveHint:false,idempotentHint:false,openWorldHint:false},securitySchemes:[{type:'oauth2',scopes:['cmeng:read']}],inputSchema:{type:'object',required:['projectId'],additionalProperties:false,properties:{projectId:{type:'string',description:'Exact authorized CMeng project code.'},objective:{type:'string',maxLength:4000},metric:{type:'string'},authorityIds:{type:'array',items:{type:'string'},maxItems:8},filters:{type:'array',maxItems:8,items:{type:'object',required:['field','operator','value'],additionalProperties:false,properties:{field:{type:'string'},operator:{type:'string',enum:['eq','contains','lt','lte','gt','gte','between']},value:{type:['string','number','boolean']},upper:{type:['string','number','boolean']}}}},groupBy:{type:'array',items:{type:'string'},maxItems:3},rankBy:{type:'string'},direction:{type:'string',enum:['asc','desc']},limit:{type:'integer',minimum:1},asOf:{type:'string',description:'Historical YYYY-MM-DD; CMeng discloses unavailable historical evidence.'},analysisId:{type:'string'},recordId:{type:'string'},traceId:{type:'string'},query:{type:'string'},batchToken:{type:'string'}}}}));
type Authorization={clientId:string;redirectUri:string;resource:string;challenge:string;state:string};
type FormTicket={userId:string;expires:number;authorization?:Authorization};
type Code={connectionId:string;clientId:string;redirectUri:string;resource:string;challenge:string;expires:number};

export class ExternalHttp {
  private forms=new Map<string,FormTicket>();
  private codes=new Map<string,Code>();
  private registrationTimes:number[]=[];
  constructor(readonly access:ExternalAccess,readonly service:ExternalIntelligenceService,readonly askSettingsPath?:string){}
  private send(res:ServerResponse,status:number,value:unknown){res.writeHead(status,{'content-type':'application/json; charset=utf-8','cache-control':'no-store','x-content-type-options':'nosniff'});res.end(JSON.stringify(value));}
  private page(res:ServerResponse,title:string,body:string,script=''){
    // Native form POSTs use Origin: null under no-referrer, even within CMeng.
    // Keep the origin for our forms while withholding referrers from other sites.
    const nonce=secret();res.writeHead(200,{'content-type':'text/html; charset=utf-8','cache-control':'no-store','referrer-policy':'same-origin','x-frame-options':'DENY','x-content-type-options':'nosniff','content-security-policy':`default-src 'none'; style-src 'unsafe-inline'; script-src 'nonce-${nonce}'; connect-src 'self'; form-action 'self'; frame-ancestors 'none'; base-uri 'none'`});
    res.end('<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>'+escape(title)+' · CMeng</title><style>body{font:16px/1.55 system-ui;color:#233b50;background:#f4f7fb;margin:0}main{max-width:960px;margin:40px auto;padding:28px;background:white;border:1px solid #dce5ed;border-radius:12px}h1{font-size:28px}h2{font-size:20px}a{color:#285f91}button{background:#2d6496;color:#fff;border:0;border-radius:6px;padding:11px 17px;font:inherit;cursor:pointer}label{display:block;margin:10px 0}input,select{font:inherit;padding:8px;max-width:100%;box-sizing:border-box}input[type=checkbox]{margin-right:10px}fieldset,article{border:1px solid #dce5ed;border-radius:8px;padding:14px;margin:14px 0}code{overflow-wrap:anywhere}small{color:#55697c}.notice{padding:14px;background:#fff5dd;border-radius:8px}.buttons{display:flex;gap:12px;flex-wrap:wrap}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:10px;border-bottom:1px solid #ddd;overflow-wrap:anywhere}#message{white-space:pre-wrap}button:disabled{opacity:.6}@media(max-width:600px){main{margin:10px;padding:16px}table{font-size:13px}}</style><main><a href="/">CMeng projects</a><h1>'+escape(title)+'</h1>'+body+'</main>'+(script?'<script nonce="'+nonce+'">'+script+'</script>':'')+'</html>');
  }
  private async body(req:IncomingMessage){let size=0;const chunks:Buffer[]=[];for await(const part of req){size+=part.length;if(size>65536)fail(413,'request_too_large','This request is too large.');chunks.push(Buffer.from(part));}const raw=Buffer.concat(chunks).toString();if(String(req.headers['content-type']??'').startsWith('application/x-www-form-urlencoded')){const values=new URLSearchParams(raw);return Object.fromEntries([...new Set(values.keys())].map(k=>[k,values.getAll(k).length>1?values.getAll(k):values.get(k)]));}try{return JSON.parse(raw||'{}');}catch{fail(400,'invalid_request','The request could not be read.');}}
  private origin(req:IncomingMessage,required=false){const supplied=req.headers.origin;if((required&&!supplied)||supplied&&supplied!==this.access.configured(false).publicOrigin)fail(403,'origin_denied','Open this action from CMeng.');}
  private bearer(req:IncomingMessage){const value=req.headers.authorization;if(typeof value!=='string'||!/^Bearer cmeng_ext_[A-Za-z0-9_-]{43}$/.test(value))fail(401,'invalid_token','Connect your account before asking about a project.');return value!.slice(7);}
  private gc(){const now=this.access.now();for(const [k,v]of this.forms)if(v.expires<=now)this.forms.delete(k);for(const[k,v]of this.codes)if(v.expires<=now)this.codes.delete(k);}
  private ticket(user:ExternalUser,authorization?:Authorization){this.gc();if(this.forms.size>=1000)fail(429,'request_limit','Too many connection requests. Please try again shortly.');const value=secret();this.forms.set(digest(value),{userId:user.id,expires:this.access.now()+600000,...authorization?{authorization}:{}});return '<input type="hidden" name="csrf" value="'+value+'">';}
  private consumeTicket(user:ExternalUser,value:unknown){this.gc();const key=digest(String(value)),t=this.forms.get(key);if(!t||t.userId!==user.id)fail(403,'form_expired','This form expired. Open External AI Access again.');this.forms.delete(key);return t!;}
  private authorization(url:URL):Authorization{
    const q=url.searchParams,clientId=q.get('client_id')??'',client=this.access.clients().find(c=>c.id===clientId),redirectUri=q.get('redirect_uri')??'',resource=q.get('resource')??'',challenge=q.get('code_challenge')??'',state=q.get('state')??'';
    if(!client||!client.redirectUris.includes(redirectUri)||q.get('response_type')!=='code'||q.get('code_challenge_method')!=='S256'||!/^[A-Za-z0-9_-]{43}$/.test(challenge)||resource!==this.access.configured().publicOrigin+'/external-ai/mcp'||state.length>2048||q.get('scope')&&q.get('scope')!=='cmeng:read')fail(400,'invalid_request','The external assistant supplied an invalid connection request.');
    return {clientId,redirectUri,resource,challenge,state};
  }
  private projectChoices(user:ExternalUser){return Object.entries(user.projects).filter(([id])=>this.access.projectEnabled(id)).map(([id,ds])=>'<label><input type="checkbox" name="projects" value="'+escape(id)+'">'+escape(id)+' <small>'+escape(ds.filter(d=>this.access.configured().projects[id]!.domains.includes(d)).join(', '))+'</small></label>').join('');}
  async handle(req:IncomingMessage,res:ServerResponse):Promise<boolean>{
    const url=new URL(req.url??'/','http://localhost'),path=url.pathname;
    if(!path.startsWith('/external-ai')&&!path.startsWith('/.well-known/oauth-')&&path!=='/settings/ask-ai')return false;
    try{
      if(path==='/settings/ask-ai'){
        let user:ExternalUser;try{user=this.access.identity(req);}catch{this.page(res,'Built-in Ask CMeng settings','<p>Open your private activation link in this browser to configure your own paid AI account.</p><p>Local project questions remain available without an API key.</p>');return true;}
        if(!user!.externalAdmin||!this.askSettingsPath)fail(403,'owner_required','Only the configured owner can change the paid AI account.');
        if(req.method==='POST'){this.origin(req,true);const body=await this.body(req);this.consumeTicket(user!,body.csrf);try{saveManagedAskSettings(this.askSettingsPath!,body.model,body.apiKey);}catch(e){fail(400,'model_configuration_invalid',e instanceof Error?e.message:'Model settings could not be saved.');}this.access.audit(null,'built_in_model_configured',null,[],0,'allowed',user!.id);res.writeHead(303,{location:'/settings/ask-ai?saved=1','cache-control':'no-store'});res.end();return true;}
        if(req.method!=='GET')fail(405,'method_not_allowed','Open the settings page.');
        let saved:ReturnType<typeof readManagedAskSettings>=null,settingsError='';try{saved=readManagedAskSettings(this.askSettingsPath!);}catch{settingsError='The saved AI settings could not be read. Enter your key again to repair them. Local calculations remain available.';}
        this.page(res,'Built-in Ask CMeng settings',(settingsError?'<p role="alert">'+escape(settingsError)+'</p>':'')+(url.searchParams.get('saved')?'<p class="notice">Saved. Your next Ask CMeng request will use these settings. The key has not yet been tested with OpenAI.</p>':'')+'<p>This configures AI interpretation inside CMeng. Your external ChatGPT connection is separate.</p><p>CPI, SPI, dates and other questions CMeng can fully calculate remain local. AI interpretation sends selected project information to OpenAI and incurs charges on your API account.</p><form method="post" action="/settings/ask-ai">'+this.ticket(user!)+'<label>Model<select name="model">'+ownerOpenAiModels.map(m=>'<option value="'+m+'"'+((saved?.model??'gpt-5-mini')===m?' selected':'')+'>'+m+'</option>').join('')+'</select></label><label>OpenAI API key<input type="password" name="apiKey" autocomplete="off" spellcheck="false" placeholder="'+(saved?'Leave blank to keep the saved key':'Enter your API key here')+'"></label><p>No GPT-6 model or automatic model upgrade is configured. The saved key is never shown or returned to the browser.</p><p>Paid interpretation is available in the browser where you activated owner access. Local project calculations remain available through the existing app.</p><button>Save my AI settings</button></form><p>'+escape(saved?'Saved model: '+saved.model+' · API key saved':'No API key has been saved in this setup.')+'</p><p><a href="/external-ai">Manage external AI connections</a></p>');return true;
      }
      if(path==='/external-ai'&&req.method==='GET'){
        let p;try{p=this.access.configured();}catch(e){this.page(res,'External AI Access','<p>External AI Access is not enabled for this installation.</p><p><a href="/settings/ask-ai">Built-in Ask CMeng settings</a></p>');return true;}
        let user:ExternalUser;try{user=this.access.identity(req);}catch{this.page(res,'External AI Access','<p>Open your private activation link in this browser to connect your own AI account.</p><p>Your existing CMeng projects and Ask CMeng remain available.</p>');return true;}
        const connections=this.access.list(user!);
        this.page(res,'External AI Access','<p>Connect your own AI assistant to read live project figures. It cannot upload, approve or change project records.</p><p>Connection address:</p><p><code>'+escape(p.publicOrigin+'/external-ai/mcp')+'</code></p><ol><li>Add this address as a connection in your AI account.</li><li>When it opens CMeng, select the projects you want it to read.</li><li>Return to your AI account and ask a project question.</li></ol><p>CMeng does not call another AI model for these requests. Your external assistant uses its own account.</p><h2>Project access</h2>'+Object.entries(user!.projects).map(([id])=>'<form method="post" action="/external-ai/manage">'+this.ticket(user!)+'<input type="hidden" name="action" value="project"><input type="hidden" name="projectId" value="'+escape(id)+'"><input type="hidden" name="disabled" value="'+String(this.access.projectEnabled(id))+'"><p><b>'+escape(id)+'</b> · '+(this.access.projectEnabled(id)?'Enabled':'Disabled')+' '+(user!.externalAdmin?'<button>'+ (this.access.projectEnabled(id)?'Disable external access':'Enable external access')+'</button>':'')+'</p></form>').join('')+'<h2>Your connections</h2>'+(connections.length?connections.map(c=>'<article><b>'+escape(this.access.clients().find(x=>x.id===c.clientId)?.name??'External assistant')+'</b><p>'+escape(Object.keys(c.projects).join(', '))+'</p><p>'+escape(c.profile==='audit'?'Owner / audit access':'Customer access')+' · '+escape(c.status==='active'&&!c.lastUsedAt?'Waiting for its first project question':c.status)+'</p><small>Connected '+escape(c.createdAt)+' · Last use '+escape(c.lastUsedAt??'Not used yet')+' · Expires '+escape(c.expiresAt)+'</small>'+(c.status==='active'?'<form method="post" action="/external-ai/manage">'+this.ticket(user!)+'<input type="hidden" name="action" value="revoke"><input type="hidden" name="connectionId" value="'+escape(c.id)+'"><button>Disconnect</button></form>':'')+'</article>').join(''):'<p>No AI account has completed its connection yet.</p>')+'<details><summary>Usage</summary><pre>'+escape(JSON.stringify(this.access.usage(user!),null,2))+'</pre></details>');return true;
      }
      if(path==='/external-ai/activate'&&req.method==='GET'){
        this.page(res,'Activate your External AI Access','<p>This private link opens connection management for the CMeng owner. Your regular project screens keep their current login arrangements.</p><button id="activate">Activate my connection access</button><p id="message" role="status"></p>',`const token=location.hash.slice(1);history.replaceState(null,'',location.pathname);document.getElementById('activate').onclick=async()=>{const b=document.getElementById('activate');b.disabled=true;try{const r=await fetch('/external-ai/activate',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({token})});const v=await r.json();if(!r.ok)throw Error(v.message);location.assign('/external-ai');}catch(e){document.getElementById('message').textContent=e.message;b.disabled=false;}};`);return true;
      }
      if(path==='/external-ai/activate'&&req.method==='POST'){this.origin(req,true);const body=await this.body(req),token=this.access.activateOwner(body.token);res.setHeader('set-cookie','cmeng_external_owner='+token+'; HttpOnly; SameSite=Lax; Path=/; Max-Age=604800'+(this.access.configured(false).publicOrigin.startsWith('https:')?'; Secure':''));this.send(res,200,{activated:true});return true;}
      const p=this.access.configured(),origin=p.publicOrigin,resource=origin+'/external-ai/mcp';
      if(req.method==='GET'&&(path==='/.well-known/oauth-protected-resource'||path==='/.well-known/oauth-protected-resource/external-ai/mcp')){this.send(res,200,{resource,authorization_servers:[origin],scopes_supported:['cmeng:read'],bearer_methods_supported:['header']});return true;}
      if(req.method==='GET'&&path==='/.well-known/oauth-authorization-server'){this.send(res,200,{issuer:origin,authorization_response_iss_parameter_supported:true,authorization_endpoint:origin+'/external-ai/authorize',token_endpoint:origin+'/external-ai/token',registration_endpoint:origin+'/external-ai/register',revocation_endpoint:origin+'/external-ai/revoke',response_types_supported:['code'],grant_types_supported:['authorization_code','refresh_token'],token_endpoint_auth_methods_supported:['none'],code_challenge_methods_supported:['S256'],scopes_supported:['cmeng:read']});return true;}
      if(path==='/external-ai/manage'&&req.method==='POST'){this.origin(req,true);const user=this.access.identity(req),body=await this.body(req);this.consumeTicket(user,body.csrf);if(body.action==='revoke')this.access.revoke(user,String(body.connectionId));else if(body.action==='project')this.access.disableProject(user,String(body.projectId),body.disabled==='true');else fail(400,'invalid_action','Choose a listed connection action.');res.writeHead(303,{location:'/external-ai','cache-control':'no-store'});res.end();return true;}
      if(path==='/external-ai/register'&&req.method==='POST'){
        this.origin(req);this.registrationTimes=this.registrationTimes.filter(t=>t>this.access.now()-60000);if(this.registrationTimes.length>=20)fail(429,'registration_limit','Too many registration attempts.');this.registrationTimes.push(this.access.now());const body=await this.body(req);
        if(body.token_endpoint_auth_method&&body.token_endpoint_auth_method!=='none'||body.grant_types&&!body.grant_types.every((v:string)=>['authorization_code','refresh_token'].includes(v)))fail(400,'invalid_client_metadata','Only the public authorization-code client flow is supported.');
        const client=this.access.registerClient(body.client_name??'External assistant',body.redirect_uris);this.send(res,201,{client_id:client.id,client_name:client.name,redirect_uris:client.redirectUris,token_endpoint_auth_method:'none',grant_types:['authorization_code','refresh_token'],response_types:['code']});return true;
      }
      if(path==='/external-ai/authorize'&&req.method==='GET'){
        const auth=this.authorization(url);let user:ExternalUser;try{user=this.access.identity(req);}catch{this.page(res,'Open your private activation link','<p>Open your CMeng activation link in this same browser, then return to this connection request and reload it.</p><p>The assistant has not received project access.</p>');return true;}
        const client=this.access.clients().find(c=>c.id===auth.clientId)!;
        this.page(res,'Connect '+client.name,'<p>Select the projects this assistant may read. Each question uses one project. It cannot change your records.</p><form method="post" action="/external-ai/authorize">'+this.ticket(user!,auth)+'<fieldset><legend>Projects</legend>'+this.projectChoices(user!)+'</fieldset><label>Access type<select name="profile"><option value="customer">Customer — project questions</option>'+(user!.allowAudit?'<option value="audit">Owner / audit — detailed checks</option>':'')+'</select></label><p>Expires within '+Math.round(this.access.limits('customer').connectionSeconds/86400)+' days. You can disconnect it at any time.</p><button>Connect selected projects</button></form>');return true;
      }
      if(path==='/external-ai/authorize'&&req.method==='POST'){
        this.origin(req,true);const user=this.access.identity(req),body=await this.body(req),ticket=this.consumeTicket(user,body.csrf),a=ticket.authorization;if(!a)fail(400,'invalid_request','Restart the connection from your AI account.');
        const selected=Array.isArray(body.projects)?body.projects:[body.projects].filter(Boolean),projects=Object.fromEntries(selected.map((id:unknown)=>{if(typeof id!=='string')fail(400,'project_required','Choose a project.');return [id,(user.projects[id as string]??[]).filter(d=>p.projects[id as string]?.domains.includes(d))];}));
        const connection=this.access.create(user,{clientId:a!.clientId,profile:body.profile,projects});const code=secret();this.codes.set(digest(code),{connectionId:connection.id,clientId:a!.clientId,redirectUri:a!.redirectUri,resource:a!.resource,challenge:a!.challenge,expires:this.access.now()+300000});const back=new URL(a!.redirectUri);back.searchParams.set('code',code);back.searchParams.set('state',a!.state);back.searchParams.set('iss',origin);res.writeHead(303,{location:back.toString(),'cache-control':'no-store','referrer-policy':'no-referrer'});res.end();return true;
      }
      if(path==='/external-ai/token'&&req.method==='POST'){
        this.origin(req);const body=await this.body(req);if(body.grant_type==='refresh_token'){this.send(res,200,this.access.refresh(String(body.refresh_token),String(body.client_id),String(body.resource)));return true;}
        this.gc();const key=digest(String(body.code)),code=this.codes.get(key);
        if(body.grant_type!=='authorization_code'||!code||code.clientId!==body.client_id||code.redirectUri!==body.redirect_uri||code.resource!==body.resource||typeof body.code_verifier!=='string'||!/^[A-Za-z0-9._~-]{43,128}$/.test(body.code_verifier)||createHash('sha256').update(body.code_verifier).digest('base64url')!==code.challenge)fail(400,'invalid_grant','The connection request is expired or invalid. Restart account linking.');
        this.codes.delete(key);this.send(res,200,this.access.issue(code!.connectionId,code!.resource));return true;
      }
      if(path==='/external-ai/revoke'&&req.method==='POST'){this.origin(req);const body=await this.body(req);this.access.revokeToken(String(body.token),String(body.client_id));this.send(res,200,{});return true;}
      if(path==='/external-ai/mcp'){
        this.origin(req);if(req.method!=='POST'){res.setHeader('allow','POST');this.send(res,405,{error:'method_not_allowed'});return true;}
        const body=await this.body(req);if(!body||body.jsonrpc!=='2.0'||Array.isArray(body)||typeof body.method!=='string')fail(400,'invalid_request','Send a single JSON-RPC request.');
        if(body.method==='notifications/initialized'&&body.id===undefined){res.writeHead(202);res.end();return true;}
        if(body.id===undefined||typeof body.id!=='string'&&typeof body.id!=='number')fail(400,'invalid_request','A request identifier is required.');
        const rpc=(result:unknown)=>this.send(res,200,{jsonrpc:'2.0',id:body.id,result});
        if(body.method==='initialize'){rpc({protocolVersion:['2025-11-25','2025-06-18','2025-03-26'].includes(body.params?.protocolVersion)?body.params.protocolVersion:'2025-11-25',capabilities:{tools:{listChanged:false}},serverInfo:{name:'CMeng External Intelligence',version:'1.0.0'},instructions:'Read-only, question-scoped CMeng project facts. Check get_project_state before current conclusions. Follow evidence batch tokens before claiming completeness. Never treat missing values as zero or external interpretation as official project approval.'});return true;}
        if(body.method==='ping'){rpc({});return true;}
        if(body.method==='tools/list'){rpc({tools:externalTools});return true;}
        if(body.method!=='tools/call'){this.send(res,200,{jsonrpc:'2.0',id:body.id,error:{code:-32601,message:'Only read-only project tools are available.'}});return true;}
        const token=this.bearer(req);try{const result=await this.service.execute(token,body.params?.name,body.params?.arguments);rpc({content:[{type:'text',text:JSON.stringify(result)}],structuredContent:result,isError:false});}catch(e){if(e instanceof ExternalError&&e.status===401)throw e;const message=e instanceof ExternalError?e.message:'The requested project analysis could not be completed.';rpc({content:[{type:'text',text:JSON.stringify({error:e instanceof ExternalError?e.code:'analysis_unavailable',message})}],isError:true});}return true;
      }
      if(path.startsWith('/external-ai/api/')&&req.method==='POST'){this.origin(req);const operation=path.slice('/external-ai/api/'.length) as Capability;this.send(res,200,await this.service.execute(this.bearer(req),operation,await this.body(req) as Query));return true;}
      this.send(res,404,{error:'not_found'});return true;
    }catch(e){const status=e instanceof ExternalError?e.status:500;if(status===401){const origin=this.access.policy()?.publicOrigin;if(origin)res.setHeader('www-authenticate','Bearer resource_metadata="'+origin+'/.well-known/oauth-protected-resource/external-ai/mcp", scope="cmeng:read"');}this.send(res,status,{error:e instanceof ExternalError?e.code:'external_request_failed',message:e instanceof ExternalError?e.message:'The external connection request could not be completed.'});return true;}
  }
}
