import type {AnalysisPlan,AuthorityDescriptor,Cell,CoverageManifest,Domain,ProjectScope} from '../../project-ask/src/types';
import type {EvidenceItem} from '../../project-ask/src/evidence';
export type Profile='customer'|'audit';
export type Capability='describe_capabilities'|'get_project_state'|'get_project_metric'|'run_project_analysis'|'get_ranked_result'|'get_related_records'|'get_evidence_trace'|'search_evidence'|'get_analysis_batch'|'check_analysis_freshness';
export const capabilities:Capability[]=['describe_capabilities','get_project_state','get_project_metric','run_project_analysis','get_ranked_result','get_related_records','get_evidence_trace','search_evidence','get_analysis_batch','check_analysis_freshness'];
export interface Limits {requestsPerMinute:number;dailyRequests:number;monthlyRequests:number;recordsPerResponse:number;recordsPerSession:number;recordsPerMonth:number;retrievalsPerSession:number;concurrentRequests:number;activeSessions:number;sessionSeconds:number;connectionSeconds:number;responseBytes:number;sessionBytes:number;evidenceExcerpts:number;maxRank:number}
export const customerLimits:Limits={requestsPerMinute:30,dailyRequests:500,monthlyRequests:5000,recordsPerResponse:100,recordsPerSession:1000,recordsPerMonth:10000,retrievalsPerSession:25,concurrentRequests:2,activeSessions:12,sessionSeconds:1800,connectionSeconds:2592000,responseBytes:196608,sessionBytes:4194304,evidenceExcerpts:8,maxRank:100};
export const auditLimits:Limits={...customerLimits,recordsPerResponse:500,recordsPerSession:10000,recordsPerMonth:100000,sessionBytes:16777216,responseBytes:1048576,activeSessions:30,maxRank:500};
export interface ExternalUser {id:string;enabled:boolean;workspaceId:string;externalAdmin?:boolean;allowAudit?:boolean;projects:Record<string,Domain[]>}
export interface ExternalClient {id:string;name:string;redirectUris:string[];launchUrl?:string}
export interface ExternalPolicy {schemaVersion:1;enabled:boolean;publicOrigin:string;workspaceId:string;identity:{issuer:string;audience:string;publicKeyPem:string;cookieName?:string};ownerActivation?:{userId:string;hash:string;expiresAt:string};registrationRedirectOrigins?:string[];users:ExternalUser[];projects:Record<string,{enabled:boolean;domains:Domain[]}>;clients:ExternalClient[];limits?:{customer?:Partial<Limits>;audit?:Partial<Limits>}}
export interface Connection {id:string;userId:string;workspaceId:string;clientId:string;profile:Profile;projects:Record<string,Domain[]>;createdAt:string;expiresAt:string;revokedAt:string|null;lastUsedAt:string|null}
export interface Query {projectId:string;objective?:string;authorityIds?:string[];metric?:string;filters?:AnalysisPlan['filters'];groupBy?:string[];rankBy?:string;direction?:'asc'|'desc';limit?:number;asOf?:string;analysisId?:string;recordId?:string;traceId?:string;query?:string;batchToken?:string}
export interface ProjectManifest {projectId:string;projectVersion:number;dataDate:string|null;programmeRevision:string|null;authorityState:string;lastControlledUpdate:string|null;authorityVersions:Record<string,{version:number;basis:'project-version';independentlyVersioned:false}>;changedDomains:null;snapshotId:null}
export interface ExternalAnalysis {id:string;createdAt:string;scope:ProjectScope;plan:AnalysisPlan;items:EvidenceItem[];coverage:CoverageManifest;traces:{id:string;authorityId:string;basis:string;sourceRefs:string[];state:string;dataDate:string|null;exclusions:string[]}[];recordIds:string[];sourceRefs:string[];factsHash:string;llmInvoked:false}
export interface AnalysisSession {id:string;connectionId:string;userId:string;workspaceId:string;projectId:string;projectVersion:number;dataDate:string|null;createdAt:string;expiresAt:string;authorityIds:string[];objectiveHash:string;retrievals:number;recordsReturned:number;deliveredItemIds:string[];batchTokens:Record<string,number>;analysis:ExternalAnalysis}
export interface ExternalBackend {catalogue:AuthorityDescriptor[];state(projectId:string,authorityIds:string[]):Promise<ProjectManifest>;analyse(projectId:string,user:ExternalUser,plan:AnalysisPlan):Promise<ExternalAnalysis>;retrieve(projectId:string,user:ExternalUser,session:AnalysisSession,operation:'get_related_records'|'get_evidence_trace'|'search_evidence',query:Query,limit:number):Promise<{items:EvidenceItem[];matching:number;qualification:string}>}
export class ExternalError extends Error {constructor(public status:number,public code:string,message:string){super(message)}}
export const fail=(status:number,code:string,message:string):never=>{throw new ExternalError(status,code,message)};
export const domains:Domain[]=['schedule','boq','delivery','commercial','claims','evidence'];
export const scalar=(v:unknown):v is Cell=>v===null||typeof v==='string'||typeof v==='boolean'||typeof v==='number'&&Number.isFinite(v);
