export const deliveryPages=[
 ['delivery-control','Delivery Control','Cross-package scope, supply, construction and handover exceptions.','package'],
 ['procurement-packages','Procurement Packages','Required actions, delivery exposure and the package lifecycle.','package'],
 ['material-tracking','Material Tracking','Required, ordered, delivered, accepted and installed quantities by compatible unit.','package'],
 ['long-lead','Long Lead','Latest procurement actions using controlled programme need dates and evidenced lead times.','package'],
 ['delivery-submittals','Submittals','Submission, review and approval position with revision control.','submittal'],
 ['procurement-scurves','Procurement S-Curves','Separate throughput, value, weighted progress, material and approval curves.','package'],
 ['delivery-suppliers','Suppliers & Subcontractors','Linked package delivery and performance.','supplier'],
 ['delivery-design','RFI & Design','Required information, response dates and design blockers.','design'],
 ['construction-discipline','Discipline Progress','Existing programme progress by governed discipline and workfront links.','workfront'],
 ['construction-locations','Location / Floor / Zone','Workfront progress through the governed project location hierarchy.','location'],
 ['construction-readiness','Construction Readiness','Applicable workfront gates, confirmed blockers and unresolved prerequisites.','workfront'],
 ['procurement-readiness','Procurement Readiness','Applicable package gates, quantities and programme need-date exposure.','package'],
 ['delivery-quality','Quality & Inspections','NCR, WIR, MIR, inspections, verification and rework.','quality'],
 ['delivery-permits','Permits & Authorities','Issued permits, validity and workfront constraints.','permit'],
 ['delivery-hse','Construction HSE','Incidents, inspections and exposure-based safety rates.','hse'],
 ['delivery-commissioning','Testing & Commissioning','System tests, outcomes, retests and acceptance evidence.','commissioning'],
 ['delivery-assets','Asset & System Handover','Installation, commissioning, documentation and handover relationships.','asset'],
 ['delivery-closeout','Snag & Closeout','Outstanding construction work, rectification and verified closure.','snag'],
 ['delivery-spares','Spares & Special Tools','Required, delivered, accepted, stored and handed-over quantities.','spare'],
 ['handover-readiness','Handover Readiness','Accepted requirements against a confirmed handover population.','handover'],
 ['delivery-weather','Weather / Disruption Evidence','Recorded site disruption and links to the existing claims authority.','weather'],
 ['delivery-risks','Delivery Risks','The governed project risk register viewed by delivery consequence.','package'],
] as const;
export const isDeliveryPage=(key:string)=>deliveryPages.some(p=>p[0]===key);
